# Generated by Django 5.0.3 on 2024-03-23 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('users', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='publisher',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.custompublisher'),
            preserve_default=False,
        ),
    ]
