# Generated by Django 5.0.3 on 2024-03-13 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
