# Generated by Django 5.0.3 on 2024-03-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_publisher_email_alter_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='certificate',
            field=models.FileField(upload_to='certificate/'),
        ),
    ]
