# Generated by Django 5.0.3 on 2024-03-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_publisher_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificate/'),
        ),
    ]
