# Generated by Django 5.0.3 on 2024-03-21 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
