# Generated by Django 5.0.3 on 2024-03-17 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPublisher',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.customuser')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificate/')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
    ]
