# Generated by Django 5.0.3 on 2024-03-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_custompublisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
    ]
