# Generated by Django 5.0.3 on 2024-03-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Profile_Pic',
            field=models.ImageField(null=True, upload_to='Profile/'),
        ),
    ]
