# Generated by Django 5.0.3 on 2024-03-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompublisher',
            options={'verbose_name': 'Publisher', 'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterField(
            model_name='custompublisher',
            name='certificate',
            field=models.FileField(default=1, upload_to='certificate/'),
            preserve_default=False,
        ),
    ]
