# Generated by Django 5.0.3 on 2024-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='Profile/'),
        ),
    ]
