# Generated by Django 4.2.11 on 2024-03-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_custompublisher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompublisher',
            options={},
        ),
    ]
