# Generated by Django 5.0.3 on 2024-03-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rate', models.CharField(choices=[(1, 'very bad'), (2, 'bad'), (3, 'Neutral'), (4, 'good'), (5, 'excellent')], max_length=3)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
