# Generated by Django 5.0.3 on 2024-03-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
