# Generated by Django 4.2.11 on 2024-03-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0012_alter_rate_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
