# Generated by Django 5.0.3 on 2024-03-18 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=255, unique=True)),
                ('front_img', models.ImageField(upload_to='book/')),
                ('back_img', models.ImageField(upload_to='book/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('language', models.CharField(choices=[('Arabic', 'Arabic'), ('English', 'English'), ('French', 'French')], max_length=7)),
                ('no_of_page', models.IntegerField(blank=True, null=True)),
                ('year_of_publication', models.DateField()),
                ('total_number_of_book', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='account.author')),
            ],
        ),
    ]
