# Generated by Django 5.0.3 on 2024-03-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Arabic', 'Arabic'), ('English', 'English')], max_length=7),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_number_of_book',
            field=models.IntegerField(),
        ),
    ]
