# Generated by Django 5.0.3 on 2024-03-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default='', upload_to='book/'),
            preserve_default=False,
        ),
    ]
