# Generated by Django 4.2.11 on 2024-03-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Arabic', 'Arabic'), ('English', 'English')], max_length=7),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_number_of_book',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
