# Generated by Django 5.0.3 on 2024-03-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_language_alter_book_total_number_of_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Arabic', 'Arabic'), ('English', 'English'), ('French', 'French')], max_length=7),
        ),
    ]
