# Generated by Django 5.0.3 on 2024-03-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_rates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rates',
        ),
    ]
