# Generated by Django 4.2.11 on 2024-03-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('order_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
