# Generated by Django 4.2.11 on 2024-03-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_orderd',
            new_name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='book_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='book_name',
        ),
    ]
