# Generated by Django 5.0.3 on 2024-03-22 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_quantity_order_total_orderitem_total_and_more'),
        ('users', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_order_address', to='users.address'),
        ),
    ]
