# Generated by Django 4.2.11 on 2024-03-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_is_orderd_order_is_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
