# Generated by Django 5.0.3 on 2024-03-22 19:20

import creditcards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', creditcards.models.CardNumberField(blank=True, max_length=25, verbose_name=True)),
                ('expire', creditcards.models.CardExpiryField(blank=True, verbose_name=True)),
                ('security_code', creditcards.models.SecurityCodeField(blank=True, max_length=4, verbose_name=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='order.order')),
            ],
        ),
    ]
