# Generated by Django 4.2.11 on 2024-03-14 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderlist_total_price_alter_orderlist_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
