# Generated by Django 4.2.11 on 2024-03-22 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_ordered_date_alter_order_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
