# Generated by Django 4.2.11 on 2024-03-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderlist_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='product_name',
            new_name='book_name',
        ),
    ]
