# Generated by Django 4.2.11 on 2024-03-14 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_product_name_orderlist_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
