# Generated by Django 4.2.11 on 2024-03-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_options_remove_order_is_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_orderd',
            field=models.BooleanField(default=False),
        ),
    ]
