# Generated by Django 4.2.11 on 2024-03-14 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderlist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
