# Generated by Django 4.2.11 on 2024-03-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_payment_card_number_alter_payment_expire_and_more'),
        ('order', '0006_alter_order_ordered_date'),
    ]

    operations = [
    ]
