# Generated by Django 4.2.11 on 2024-03-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_merge_20240323_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
