# Generated by Django 5.0.3 on 2024-04-24 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_ordered_date_alter_order_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_time',
            field=models.TimeField(default=datetime.time(5, 10, 28, 883796)),
        ),
    ]
