# Generated by Django 4.2.11 on 2024-03-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderlist_quantity_alter_orderlist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='status',
        ),
    ]
