# Generated by Django 5.0.3 on 2024-04-24 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_ordered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.TimeField(default=datetime.time(5, 21, 59, 280567)),
        ),
    ]
