# Generated by Django 4.2.11 on 2024-03-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_orderlist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='image',
            field=models.ImageField(default='default.png', upload_to='media/orderdbooks'),
        ),
    ]
