# Generated by Django 4.2.11 on 2024-03-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_orderlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='image',
            field=models.ImageField(default='default.png', upload_to='orderdbooks'),
        ),
    ]
